server:
  port: 8110

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_cart
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

userService:
  app:
    jwtCookieName: user-service
    jwtSecret: ===========================Spring===========================
    jwtExpirationMS: 86400000

