server:
  port: 8111

spring:
  datasource:
    url: jdbc:oracle:thin:@//192.168.56.1:1521/xe
    username: C##CUONG
    password: password
    driver-class-name: oracle.jdbc.OracleDriver
  hikari:
    minimumIdle: 5
    maximumPoolSize: 20
    idleTimeout: 30000
    maxLifetime: 2000000
    connectionTimeout: 30000
    poolName: HikariPoolBooks

  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    show-sql: true

productService:
  app:
    jwtSecret: ===========================Spring===========================
    jwtExpirationMS: 86400000

minio:
  bucketName: productimages
  defaultFolder: /
  accessKey: minioadmin
  secretKey: minioadmin
  host: 127.0.0.1
  port: 9111