server:
  port: 8111

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_cart
    username: root
    password: root
  minio:
    url: ""

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

productService:
  app:
    jwtSecret: ===========================Spring===========================
    jwtExpirationMS: 86400000

minio:
  bucketName: productimages
  defaultFolder: /
  accessKey: minioadmin
  secretKey: minioadmin
  url: http://127.0.0.1:9001